version:  '3.7'
services:
    db:
        container_name: ordezkatu_vue_db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            DOCKER_MYSQL_USER: ${DOCKER_MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
        volumes:
            - ordezkatu_vue_mysql:/var/lib/mysql

    app:
        container_name: ordezkatu_vue_app
        env_file: ./.env
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        build:
            context: .
            dockerfile: docker/dev/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - DEBUGMODE=${DEBUGMODE}
        depends_on:
          - db
          - redis
        volumes:
            - '.:/usr/src/app'
            - './docker/dev/php/conf/.zsh_history:/home/www-data/.zsh_history:rw'
            - './docker/dev/php/conf/php.ini:/usr/local/etc/php/php.ini:ro'
            - './docker/dev/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
        working_dir: /usr/src/app

    nginx:
        container_name: ordezkatu_vue_nginx
        build:
            context: ./
            dockerfile: docker/dev/nginx/Dockerfile

        depends_on:
            - app
        ports:
            - "80:80"
        volumes:
#            - './public/:/usr/src/app'
            - './docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        volumes_from:
            -   app
        working_dir: /usr/src/app

    redis:
        container_name: ordezkatu_vue_redis
        image: redis:alpine
        restart: always
        ports:
            - "6380:637"
        volumes:
            - ordezkatu_vue_redis:/data

volumes:
    ordezkatu_vue_mysql:
    ordezkatu_vue_redis:

networks:
    default:
        ipam:
            config:
                - subnet: 172.193.0.0/16
